# Server-side configs
movies:
  path  : '/path/to/movies/directory'
  api   : 'api.themoviedb.org/3'
  key   : '<api_key>'
music:
  path  : '/path/to/music/directory'
  api   : 'api.spotify.com/v1'
  key   : '<access_token>'
tv:
  path  : '/path/to/tv/directory'
  api   : 'api.themoviedb.org/3'
  key   : '<api_key>'
books:
  path  : '/path/to/books/directory'
  api   : 'googleapis.com/books/v1'
  key   : '<api_key>'